알파, 베타 브랜치 체크

diff --git a/.github/workflows/build-server-service.yml b/.github/workflows/build-server-service.yml
--- a/.github/workflows/build-server-service.yml
+++ b/.github/workflows/build-server-service.yml
@@ -19,6 +19,9 @@ on:
         description: 운영 환경 배포를 하는 브랜치
         required: true
         type: string
+      check_alpha_beta_branch:
+        description: 알파, 베타 브랜치 체크 여부
+        type: string
       user_name:
         description: 배포한 사용자
         required: true
@@ -86,8 +89,16 @@ jobs:
 
     steps:
       - name: Check branch is production branch (production)
-        run: exit 255
+        run: echo "::error::only ${{ inputs.production_branch }} branch allowed for production" && exit 255
         if: (inputs.stage == 'production' || inputs.stage == 'beta-rc') && inputs.branch != inputs.production_branch
+
+      - name: Check branch is alpha branch (alpha)
+        run: echo "::error::only alpha branch allowed for alpha" && exit 255
+        if: inputs.check_alpha_beta_branch == 'true' && inputs.stage == 'alpha' && inputs.branch != 'alpha'
+
+      - name: Check branch is beta branch (beta)
+        run: echo "::error::only beta branch allowed for beta" && exit 255
+        if: inputs.check_alpha_beta_branch == 'true' && inputs.stage == 'beta' && inputs.branch != 'beta'
 
       - name: Notify build start
         run: |
@@ -114,6 +125,7 @@ jobs:
           release_message: ${{ inputs.release_message }}
           working_directory: ${{ inputs.working_directory }}
           production_branch: ${{ inputs.production_branch }}
+          check_alpha_beta_branch: ${{ inputs.check_alpha_beta_branch }}
           user_name: ${{ inputs.user_name }}
           stage: ${{ inputs.stage }}
           branch: ${{ inputs.branch }}
diff --git a/build-server-service/action.yml b/build-server-service/action.yml
--- a/build-server-service/action.yml
+++ b/build-server-service/action.yml
@@ -17,6 +17,9 @@ inputs:
     description: 운영 환경 배포를 하는 브랜치
     required: true
     type: string
+  check_alpha_beta_branch:
+    description: 알파, 베타 브랜치 체크 여부
+    type: string
   user_name:
     description: 배포한 사용자
     required: true
@@ -93,8 +96,18 @@ runs:
 
     - name: Check branch is production branch (production)
       shell: bash
-      run: exit 255
+      run: echo "::error::only ${{ inputs.production_branch }} branch allowed for production" && exit 255
       if: (inputs.stage == 'production' || inputs.stage == 'beta-rc') && inputs.branch != inputs.production_branch
+
+    - name: Check branch is alpha branch (alpha)
+      shell: bash
+      run: echo "::error::only alpha branch allowed for alpha" && exit 255
+      if: inputs.check_alpha_beta_branch == 'true' && inputs.stage == 'alpha' && inputs.branch != 'alpha'
+
+    - name: Check branch is beta branch (beta)
+      shell: bash
+      run: echo "::error::only beta branch allowed for beta" && exit 255
+      if: inputs.check_alpha_beta_branch == 'true' && inputs.stage == 'beta' && inputs.branch != 'beta'
 
     - name: Configure AWS credentials for push to ECR
       uses: aws-actions/configure-aws-credentials@v1-node16
